/*
 * TIMER1_types.h
 *
 *  Created on: Mar 3, 2023
 *      Author: tarek
 */

#ifndef TIMER1_TIMER1_TYPES_H_
#define TIMER1_TIMER1_TYPES_H_





typedef enum{
	TIMER1_MODE_SELECTOR_NORMAL = 0x00,
	TIMER1_MODE_SELECTOR_PWM_PC = 0x40,
	TIMER1_MODE_SELECTOR_CTC = 0x08,			//Clear Timer On Compare Match
	TIMER1_MODE_SELECTOR_FAST_PWM = 0x48
}TIMER1_MODE_SELECTOR;


typedef enum{
	OUTPUT_COMPARE_Mode_NORMAL = 0x00,
	OUTPUT_COMPARE_Mode_RESERVER= 0x10,			//Also it named as Toggle in non_PWM Mode
	OUTPUT_COMPARE_Mode_CLEAR= 0x20,
	OUTPUT_COMPARE_Mode_SET= 0x30
}TIMER1_OUTPUT_COMPARE_MODE;


typedef enum{
	TIMER1_NO_CLK_SOURCE,
	TIMER1_CLK_SOURCE_0_PRESCALING,
	TIMER1_CLK_SOURCE_8_PRESCALING,
	TIMER1_CLK_SOURCE_64_PRESCALING,
	TIMER1_CLK_SOURCE_256_PRESCALING,
	TIMER1_CLK_SOURCE_1024_PRESCALING,
	TIMER1_CLK_SOURCE_EXT_FALLING_EDGE,
	TIMER1_CLK_SOURCE_EXT_RISING_EDGE
}TIMER1_CLK_SOURCE;




#endif /* TIMER1_TIMER1_TYPES_H_ */
